In [1]:
## bibliotecas

import pandas as pd

## Lendo Modelo Salvo No Note Anterior

In [3]:
model = pd.read_pickle('modelo_tree.pkl')

model

model       (ArbitraryNumberImputer(arbitrary_number=26.0,...
features    Index(['qtdeRecencia', 'freqDias', 'freqTransa...
auc_test                                             0.856528
dtype: object

## Supondo Que Os Dados Do Note Anterior Sejam Novos Dados

In [4]:
## importando os dados

df = pd.read_csv('dados_pontos.csv', sep=';')

df

,dtRef,idCustomer,Name,qtdeRecencia,freqDias,freqTransacoes,qtdListaPresença,qtdChatMessage,qtdTrocaPontos,qtdResgatarPonei,...,pctListaPresença,pctChatMessage,pctTrocaPontos,pctResgatarPonei,pctPresençaStreak,qtdePontosGanhos,qtdePontosGastos,qtdePontosSaldo,avgRecorrencia,flActive
0,2024-03-31,000ff655-fa9f-4baa-a108-47f581ec52a1,cajuuh,2.0,11,188,10,175,1,1,...,0.053191,0.930851,0.005319,0.005319,0.005319,1275,-1000,275,2.500000,1
1,2024-04-05,000ff655-fa9f-4baa-a108-47f581ec52a1,cajuuh,1.0,12,192,12,177,1,1,...,0.062500,0.921875,0.005208,0.005208,0.005208,1377,-1000,377,1.454545,1
2,2024-03-03,0097ab76-4637-4ece-8ebc-ab6abd61d662,losmundissas,24.0,1,1,1,0,0,0,...,1.000000,0.000000,0.000000,0.000000,0.000000,50,0,50,NaN,0
3,2024-03-08,0097ab76-4637-4ece-8ebc-ab6abd61d662,losmundissas,29.0,1,1,1,0,0,0,...,1.000000,0.000000,0.000000,0.000000,0.000000,50,0,50,NaN,0
4,2024-04-18,00a6d4c8-38e5-4e92-981e-4e4ac5084546,cecisssssss,1.0,3,5,3,2,0,0,...,0.600000,0.400000,0.000000,0.000000,0.000000,152,0,152,1.000000,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2230,2024-03-21,fe59fd95-d131-4d50-bb6e-10cdfa7d5f47,comunista_tropical,13.0,7,84,6,78,0,0,...,0.071429,0.928571,0.000000,0.000000,0.000000,378,0,378,2.333333,0
2231,2024-04-06,feb1a34d-202a-4224-a1b3-0e737b12dd4d,mmenoli,1.0,8,12,8,4,0,0,...,0.666667,0.333333,0.000000,0.000000,0.000000,404,0,404,2.142857,1
2232,2024-04-25,feb1a34d-202a-4224-a1b3-0e737b12dd4d,mmenoli,1.0,15,35,14,20,0,1,...,0.400000,0.571429,0.000000,0.028571,0.000000,1220,0,1220,1.571429,1
2233,2024-03-01,fecbdf63-3bf4-44e5-8b1a-0acc9d963603,cianaglima,24.0,2,13,2,11,0,0,...,0.153846,0.846154,0.000000,0.000000,0.000000,111,0,111,1.000000,0
2234,2024-03-06,fecbdf63-3bf4-44e5-8b1a-0acc9d963603,cianaglima,29.0,1,2,1,1,0,0,...,0.500000,0.500000,0.000000,0.000000,0.000000,51,0,51,NaN,0

## Predição Do Modelo

In [6]:
X = df[model['features']]

predict_proba = model['model'].predict_proba(X)[:,1]  ## essa última marcação serve para filtrar apenas os que vão continuar

predict_proba

array([0.91542939, 0.9388806 , 0.05231982, ..., 0.86512548, 0.05358537,
       0.06197712])

In [7]:
df['prob_active'] = predict_proba

df[['Name', 'prob_active']]

                    Name  prob_active
0                 cajuuh     0.915429
1                 cajuuh     0.938881
2           losmundissas     0.052320
3           losmundissas     0.063781
4            cecisssssss     0.510226
...                  ...          ...
2230  comunista_tropical     0.321510
2231             mmenoli     0.792602
2232             mmenoli     0.865125
2233          cianaglima     0.053585
2234          cianaglima     0.061977

[2235 rows x 2 columns]